
CFLAGS+=-Wall -Wextra -ggdb -O2 -Wno-unused-variable -Wno-unused-parameter -pthread

PROGS=signal signal_thread

ALL: $(PROGS)

clean:
	@ find . -type f -name '*.o' -delete
	@ find . -type f -executable -delete


